- hosts: tag_rocky

  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Check OS distribution condition
      debug:
        var: "{{ item }}"
      loop:
        - ansible_distribution
        - ansible_distribution_version
      failed_when:
        - ansible_distribution != 'Rocky' or ansible_distribution_version != '8.7'

  roles:
    - base